version: '3'
services:
  web:
    build: .
    volumes:
      - "./logs:/app/logs"
    deploy:
      replicas: 3
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: counterdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - dblogs:/var/log/mysql

volumes:
  dbdata:
  dblogs:
